package handlers

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/brendan4linux/webux/internal/learn"
	"github.com/brendan4linux/webux/internal/migration"
	"github.com/brendan4linux/webux/internal/system/network/ports"
)

// PortsHandler handles all port/socket scanning endpoints.
type PortsHandler struct {
	learn *learn.Store
}

func NewPortsHandler(ls *learn.Store) *PortsHandler {
	return &PortsHandler{learn: ls}
}

// List handles GET /api/ports — returns all listening ports with process info.
func (h *PortsHandler) List(w http.ResponseWriter, r *http.Request) {
	scanner := ports.NewScanner()

	openPorts, err := scanner.ScanListening()
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	sdSockets, _ := ports.LoadSystemdSockets()
	ports.EnrichWithSystemdSockets(openPorts, sdSockets)

	// Emit CLI echo for the learn pane
	h.learn.Echo(r.Context(), ports.CLIEquivalent(),
		"Lists all listening TCP/UDP sockets and which process owns each one")

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]interface{}{
		"ports":           openPorts,
		"systemd_sockets": sdSockets,
		"scanned_at":      time.Now().UTC(),
	})
}

// ListSystemdSockets handles GET /api/ports/sockets — systemd socket units only.
func (h *PortsHandler) ListSystemdSockets(w http.ResponseWriter, r *http.Request) {
	sdSockets, err := ports.LoadSystemdSockets()
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	h.learn.Echo(r.Context(), ports.CLIEquivalentSockets(),
		"Lists all systemd .socket units and the ports they declare")

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(sdSockets)
}

// MigrationHandler handles host migration template generation.
type MigrationHandler struct {
	learn *learn.Store
	gen   *migration.Generator
}

func NewMigrationHandler(ls *learn.Store) *MigrationHandler {
	return &MigrationHandler{
		learn: ls,
		gen:   migration.NewGenerator(),
	}
}

// Snapshot handles GET /api/migration/snapshot — capture full host state.
func (h *MigrationHandler) Snapshot(w http.ResponseWriter, r *http.Request) {
	h.learn.Echo(r.Context(),
		"ss -tulpn && systemctl list-unit-files --state=enabled && cat /etc/passwd | awk -F: '$3 >= 1000' && crontab -l",
		"Webux is collecting open ports, enabled services, users, and cron jobs to build a migration snapshot")

	snap, err := h.gen.Capture()
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(snap)
}

// Template handles GET /api/migration/template?format=markdown|yaml|ansible
func (h *MigrationHandler) Template(w http.ResponseWriter, r *http.Request) {
	format := r.URL.Query().Get("format")
	if format == "" {
		format = "markdown"
	}

	snap, err := h.gen.Capture()
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	var output string
	switch format {
	case "markdown":
		output, err = h.gen.RenderMarkdown(snap)
		h.learn.Echo(r.Context(), "# Generated by: webux migration snapshot",
			"Building a human-readable migration checklist in Markdown format")
	case "ansible":
		output, err = h.gen.RenderAnsible(snap)
		h.learn.Echo(r.Context(), "ansible-playbook migrate.yml -i inventory/new_host",
			"Generating an Ansible playbook skeleton to reproduce this host's configuration")
	case "yaml":
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(snap)
		return
	default:
		http.Error(w, fmt.Sprintf("unknown format %q — use markdown, yaml, or ansible", format), http.StatusBadRequest)
		return
	}

	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	// Set filename for download
	ext := map[string]string{"markdown": "md", "ansible": "yml"}[format]
	hostname := snap.Hostname
	if hostname == "" {
		hostname = "host"
	}
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Header().Set("Content-Disposition",
		fmt.Sprintf(`attachment; filename="webux-migration-%s.%s"`, hostname, ext))
	fmt.Fprint(w, output)
}
